// <auto-generated />
using System;
using ManteqTask.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManteqTask.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708000601_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-7888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Create a Draft request",
                            Name = "requests.create"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-7999-8999-999999999999"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Edit a Draft request",
                            Name = "requests.edit"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-7aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Submit a Draft for review",
                            Name = "requests.submit"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-7bbb-8bbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "View only the user's own requests",
                            Name = "requests.view.own"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-7ccc-8ccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "View all requests (with status/date filters)",
                            Name = "requests.view.all"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-7ddd-8ddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Approve a Submitted request",
                            Name = "requests.approve"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-7eee-8eee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Reject a Submitted request (reason required)",
                            Name = "requests.reject"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-7fff-8fff-ffffffffffff"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "View the status-change audit trail",
                            Name = "audit.view"
                        });
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStampAtIssue")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TokenFamilyId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-7222-8222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Full unrestricted access.",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-7333-8333-333333333333"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "General administrative access.",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-7444-8444-444444444444"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Standard registered user access.",
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-8777-777777777777"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Description = "Creates and manages their own requests.",
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.RolePermission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("88888888-8888-7888-8888-888888888888"),
                            RoleId = new Guid("77777777-7777-7777-8777-777777777777")
                        },
                        new
                        {
                            PermissionId = new Guid("99999999-9999-7999-8999-999999999999"),
                            RoleId = new Guid("77777777-7777-7777-8777-777777777777")
                        },
                        new
                        {
                            PermissionId = new Guid("aaaaaaaa-aaaa-7aaa-8aaa-aaaaaaaaaaaa"),
                            RoleId = new Guid("77777777-7777-7777-8777-777777777777")
                        },
                        new
                        {
                            PermissionId = new Guid("bbbbbbbb-bbbb-7bbb-8bbb-bbbbbbbbbbbb"),
                            RoleId = new Guid("77777777-7777-7777-8777-777777777777")
                        },
                        new
                        {
                            PermissionId = new Guid("cccccccc-cccc-7ccc-8ccc-cccccccccccc"),
                            RoleId = new Guid("33333333-3333-7333-8333-333333333333")
                        },
                        new
                        {
                            PermissionId = new Guid("dddddddd-dddd-7ddd-8ddd-dddddddddddd"),
                            RoleId = new Guid("33333333-3333-7333-8333-333333333333")
                        },
                        new
                        {
                            PermissionId = new Guid("eeeeeeee-eeee-7eee-8eee-eeeeeeeeeeee"),
                            RoleId = new Guid("33333333-3333-7333-8333-333333333333")
                        },
                        new
                        {
                            PermissionId = new Guid("ffffffff-ffff-7fff-8fff-ffffffffffff"),
                            RoleId = new Guid("33333333-3333-7333-8333-333333333333")
                        });
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-7111-8111-111111111111"),
                            RoleId = new Guid("22222222-2222-7222-8222-222222222222")
                        });
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-7000-8000-000000000000"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Email = "system@example.com",
                            FirstName = "system",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "system",
                            PasswordHash = "C70A4E72A68BFBAD78B7D4186D7BABE668E9D29B728F208513BF00F08A789E4E-5BBDF5344D620DBC46984385FE5C9302",
                            SecurityStamp = "0199ecd3-b844-792f-8f83-431df66c629d",
                            Username = "system"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-7111-8111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a0000000-0000-7000-8000-000000000000"),
                            Email = "aawwad172@gmail.com",
                            FirstName = "Initial",
                            IsActive = true,
                            IsVerified = true,
                            LastName = "Admin",
                            PasswordHash = "5658A3510D0C8BA1DFD6AF62A44E06736E0B8E43B25464887D6007E5688C7270-7F8784D082093474FEED885A5F977C20",
                            SecurityStamp = "0199ecd4-f5b6-7211-9ec7-ce26d0966b72",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.RefreshToken", b =>
                {
                    b.HasOne("ManteqTask.Domain.Entities.Authentication.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManteqTask.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.RolePermission", b =>
                {
                    b.HasOne("ManteqTask.Domain.Entities.Authentication.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManteqTask.Domain.Entities.Authentication.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.UserRole", b =>
                {
                    b.HasOne("ManteqTask.Domain.Entities.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManteqTask.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.Authentication.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ManteqTask.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
